apiVersion: v1
kind: Service
metadata:
  name: cbi-hospital-nginx-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
      app: cbi-hospital-nginx
  ports:
  - port: 8000
    targetPort: 80