apiVersion: v1
kind: Service
metadata:
  name: cbi-hospital-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
      app: cbi-hospital
  ports:
  - port: 8001
    targetPort: 5000

    #k exec -it cbi-hospital-75d6458bdb-fhxxd -- bash